config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pokemons#index'
  resources :pokemons

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
  end
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_and_belongs_to_many :abilities
  has_and_belongs_to_many :types
  belongs_to :color

  validates :name, presence: true, uniqueness: true
  attribute :image, default: 'https://bulma.io/images/placeholders/128x128.png'
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  protect_from_forgery prepend: true
  before_action :authenticate_user!, only: %i[new create edit update remove destroy]
  before_action :current_pokemon, only: %i[show edit update destroy]

  def index
    @pokemons = Pokemon.page(params[:page])
  end

  def show; end

  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(name: pokemon_params['name'],
                           hp: pokemon_params['hp'],
                           attack: pokemon_params['attack'],
                           defense: pokemon_params['defense'],
                           image: pokemon_params['image'] || 'https://via.placeholder.com/150')

    @pokemon.color = Color.find_by(name: pokemon_params['color'])
    @pokemon.types = [Type.find_by(name: pokemon_params['type'])]
    @pokemon.abilities = [Ability.find_or_create_by!(name: pokemon_params['ability'])]
    @pokemon.save!

    redirect_to pokemons_path
  end

  def edit; end

  def update
    @pokemon.update(pokemon_params)

    redirect_to pokemon_path(@pokemon)
  end

  def destroy
    @pokemon.destroy

    redirect_to pokemons_path
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name, :hp,
                                    :attack, :defense,
                                    :description, :color,
                                    :image, :type, :ability)
  end

  def current_pokemon
    @pokemon = Pokemon.find(params[:id])
  end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/edit.html.erb
<p class="is-size-4 has-text-centered">Edit a Pokemon</p>
<%= render "layouts/pokemon_form" %>

app/views/pokemons/index.html.erb
<ul>
  <% @pokemons.each do |pokemon| %>
    <li>
      <div class="card equal=height my-5">
        <div class="card-header">
          <div class="card-header-title">
            <%= tag.p pokemon.name, class: "title is-5" %>
          </div>
        </div>
        <%= link_to pokemon_path(pokemon) do %>
          <div class="card-image my-3 has-text-centered">
            <figure class="image is-128x128 is-inline-block">
              <%= image_tag(pokemon.image, class:"is-center") %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <div class="level is-marginless">
                  <div class="level-left">
                    <div class="level-item">
                      <%= tag.span "HP", class: "text has-text-weight-semibold" %>
                    </div>
                  </div>
                  <div class="level-right">
                    <div class="level-item">
                      <%= tag.span "#{pokemon.hp}", class: "text" %>
                    </div>
                  </div>
                </div>
                <div class="level is-marginless">
                  <div class="level-left">
                    <div class="level-item">
                      <%= tag.span "Attack", class: "text has-text-weight-semibold" %>
                    </div>
                  </div>
                  <div class="level-right">
                    <div class="level-item">
                      <%= tag.span "#{pokemon.attack}", class: "text" %>
                    </div>
                  </div>
                </div>
                <div class="level is-marginless">
                  <div class="level-left">
                    <div class="level-item">
                      <%= tag.span "Defense", class: "text has-text-weight-semibold" %>
                    </div>
                  </div>
                  <div class="level-right">
                    <div class="level-item">
                      <%= tag.span "#{pokemon.defense}", class: "text" %>
                    </div>
                  </div>
                </div>
                <div class="level is-marginless">
                  <div class="level-left">
                    <div class="level-item">
                      <%= tag.span "Main Type", class: "text has-text-weight-semibold" %>
                    </div>
                  </div>
                  <div class="level-right">
                    <div class="level-item">
                      <%= tag.span "#{pokemon.types.first.name}", class: "text" %>
                    </div>
                  </div>
                </div>
                <div class="level is-marginless">
                  <div class="level-left">
                    <div class="level-item">
                      <%= tag.span "Main Ability", class: "text has-text-weight-semibold" %>
                    </div>
                  </div>
                  <div class="level-right">
                    <div class="level-item">
                      <%= tag.span "#{pokemon.abilities.first.name}", class: "text" %>
                    </div>
                  </div>
                </div>
                <div class="level is-marginless">
                  <div class="level-left">
                    <div class="level-item">
                      <%= tag.span "Color", class: "text has-text-weight-semibold" %>
                    </div>
                  </div>
                  <div class="level-right">
                    <div class="level-item">
                      <%= tag.span "#{pokemon.color.name}", class: "text" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>
<%= paginate @pokemons, window: 2 %>

app/views/pokemons/new.html.erb
<p class="is-size-4 has-text-centered">Create a Pokemon!</p>
<%= render "layouts/pokemon_form" %>

app/views/pokemons/show.html.erb
<div class="card equal=height my-3">
  <div class="card-header">
    <div class="card-header-title">
      <%= tag.p @pokemon.name, class: "title is-5" %>
    </div>
  </div>
  <div class="card-image my-3 has-text-centered">
    <figure class="image is-128x128 is-inline-block">
      <%= image_tag(@pokemon.image, class:"is-center") %>
    </figure>
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <div class="level is-marginless">
          <div class="level-left">
            <div class="level-item">
              <%= tag.span "HP", class: "text has-text-weight-semibold" %>
            </div>
          </div>
          <div class="level-right">
            <div class="level-item">
              <%= tag.span "#{@pokemon.hp}", class: "text" %>
            </div>
          </div>
        </div>
        <div class="level is-marginless">
          <div class="level-left">
            <div class="level-item">
              <%= tag.span "Attack", class: "text has-text-weight-semibold" %>
            </div>
          </div>
          <div class="level-right">
            <div class="level-item">
              <%= tag.span "#{@pokemon.attack}", class: "text" %>
            </div>
          </div>
        </div>
        <div class="level is-marginless">
          <div class="level-left">
            <div class="level-item">
              <%= tag.span "Defense", class: "text has-text-weight-semibold" %>
            </div>
          </div>
          <div class="level-right">
            <div class="level-item">
              <%= tag.span "#{@pokemon.defense}", class: "text" %>
            </div>
          </div>
        </div>
        <div class="level is-marginless">
          <div class="level-left">
            <div class="level-item">
              <%= tag.span "Main Type", class: "text has-text-weight-semibold" %>
            </div>
          </div>
          <div class="level-right">
            <div class="level-item">
              <%= tag.span "#{@pokemon.types.first.name}", class: "text" %>
            </div>
          </div>
        </div>
        <div class="level is-marginless">
          <div class="level-left">
            <div class="level-item">
              <%= tag.span "Main Ability", class: "text has-text-weight-semibold" %>
            </div>
          </div>
          <div class="level-right">
            <div class="level-item">
              <%= tag.span "#{@pokemon.abilities.first.name}", class: "text" %>
            </div>
          </div>
        </div>
        <div class="level is-marginless">
          <div class="level-left">
            <div class="level-item">
              <%= tag.span "Color", class: "text has-text-weight-semibold" %>
            </div>
          </div>
          <div class="level-right">
            <div class="level-item">
              <%= tag.span "#{@pokemon.color.name}", class: "text" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer class="card-footer">
    <%= link_to "Edit", edit_pokemon_path(@pokemon), :class => "card-footer-item" %>
    <%= link_to 'Remove', @pokemon, method: :delete, data: { confirm: 'Are you sure?' }, :class => "card-footer-item"  %>
  </footer>
</div>