config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pokemons#index'
  resources :pokemons

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      RoR Apprenticeship example by <a href="https://github.com/renejesusgv">Rene Jesus</a>.
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar">
  <div class="navbar-brand">
    <%= link_to "Home", pokemons_path, :class => "navbar-item is-size-3 has-text-light has-background-success" %>
  </div>
  <div class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Create a Pokemon!", new_pokemon_path, :class => "navbar-item is-size-3 has-text-success has-background-white" %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <% if user_signed_in? %>
          <%= link_to "Log out", destroy_user_session_path, :method=>'delete', :class => "button is-danger" %>
          <%= link_to "Edit profile", edit_user_registration_path, :class => "button is-light"%>
        <% else %>
          <div class="buttons">
            <%= link_to "Sign up", sign_up_path, :class => "button is-success"%>
            <%= link_to "Log in", sign_in_path, :class => "button is-light" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_pokemon_form.html.erb
<%= form_with model: @pokemon do |form| %>
  <div class="card equal=height my-5">
    <div class="card-content">
      <div class="field my-2">
        <%= form.label :name, { class: "label"} %>
        <div class="control">
          <%= form.text_field :name, { class: "input", placeholder: "Pokemon's Name" }%>
        </div>
      </div>
      <div class="field my-2">
        <%= form.label :hp, { class: "label"} %>
        <div class="control">
          <%= form.number_field :hp, { class: "input", placeholder: "HP" } %>
        </div>
      </div>
      <div class="field my-2">
        <%= form.label :attack, { class: "label"} %>
        <div class="control">
          <%= form.number_field :attack, { class: "input", placeholder: "Attack"} %>
        </div>
      </div>
      <div class="field my-2">
        <%= form.label :defense, { class: "label"} %>
        <div class="control">
          <%= form.number_field :defense, { class: "input", placeholder: "Defense"} %>
        </div>
      </div>
      <div class="field my-2">
        <%= form.label :color, { class: "label"} %>
        <div class="control is-expanded">
          <div class="select is-fullwidth">
            <%= form.select :color, Color.all.map(&:name), {}, placeholder: "Color" %>
          </div>
        </div>
      </div>
      <div class="field my-2">
        <%= form.label :type, { class: "label"} %>
        <div class="control is-expanded">
          <div class="select is-fullwidth">
            <%= form.select :type, Type.all.map(&:name), {}, placeholder: "Main type" %>
          </div>
        </div>
      </div>
      <div class="field my-2">
        <%= form.label :ability, { class: "label"} %>
        <div class="control is-expanded">
          <div class="select is-fullwidth">
            <%= form.select :ability, Ability.all.map(&:name), {}, placeholder: "Main ability" %>
          </div>
        </div>
      </div>
      <div class="field my-2">
        <%= form.label :image, { class: "label"} %>
        <div class="control">
          <%= form.text_field :image, { class: "input", placeholder: "Image URL" }%>
        </div>
      </div>
    </div>
    <footer class="card-footer">
      <%= link_to "Cancel", pokemons_path, :class => "card-footer-item" %>
      <%= form.submit "Submit", class: "card-footer-item has-background-white", style:"border:none" %>
    </footer>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorApprenticeshipQ12022</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'bulma', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container is-max-desktop">
      <%= render "layouts/header" %>
      <div class="columns">
        <div class="column is-one-third is-offset-one-third my-5">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>